version: "3.9"
name: reward-management

x-build-args: &build-args
  GITHUB_TOKEN: # github token

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        <<: *build-args
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    volumes:
      - ./:/app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    restart: on-failure

  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reward_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 10s
      retries: 10
    restart: on-failure

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 10
    restart: on-failure

  localstack:
    image: localstack/localstack:3.6.0
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-southeast-1
    volumes:
      - "./aws:/etc/localstack/init/ready.d"
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 3s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:
  redis_data:
  localstack_data:
